config/routes.rb
PeladaManager::Application.routes.draw do
  get "users/new"

  root to: 'static_pages#home'

  match '/signup', to: 'users#new'

  match '/help', to: 'static_pages#help'
  match '/about', to: 'static_pages#about'
  match '/contact', to: 'static_pages#contact'

end

app/models/user.rb
# == Schema Information
#
# Table name: users
#
#  id         :integer          not null, primary key
#  name       :string(255)
#  email      :string(255)
#  created_at :datetime         not null
#  updated_at :datetime         not null
#

class User < ActiveRecord::Base
  attr_accessible :email, :name, :password, :password_confirmation
  has_secure_password

  before_save { self.email.downcase! }

  validates :name, presence: true, length: { maximum: 50 }
  VALID_EMAIL_REGEX = /\A[\w+\-.]+@[a-z\d\-.]+\.[a-z]+\z/i
  validates :email, presence: true, format: { with: VALID_EMAIL_REGEX },
  									uniqueness: { case_sensitive: false }
  validates :password, presence: true, length: { minimum: 6 }
  validates :password_confirmation, presence: true

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery
end

app/controllers/static_pages_controller.rb
class StaticPagesController < ApplicationController
  def home
  end

  def help
  end

  def about
  end

  def contact
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  def new
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
  # Returns the full title on a per-page basis.
  def full_title(page_title)
    base_title = "Pelada Manager"
    if page_title.empty?
       base_title
    else
      "#{base_title} | #{page_title}"
    end
  end
end

app/helpers/static_pages_helper.rb
module StaticPagesHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/layouts/_footer.html.erb
<footer class="footer">
	<small>
		<a href="http://railstutorial.org/">Pelada Manager</a> by Rodrigo Leote
	</small>
	<nav>
		<ul>
			<li><%= link_to "About", about_path %></li>
			<li><%= link_to "Contact", contact_path %></li>
			<li><a href="http://news.railstutorial.org/">News</a></li>
		</ul>
	</nav>
</footer>

app/views/layouts/_header.html.erb
<header class="navbar navbar-fixed-top navbar-inverse">
	<div class="navbar-inner">
		<div class="container">
			<%= link_to "sample app", '#', id: "logo" %>
			<nav>
				<ul class="nav pull-right">
					<li><%= link_to "Home", root_path %></li>
					<li><%= link_to "Help", help_path %></li>
					<li><%= link_to "Sign in", '#' %></li>
				</ul>
			</nav>
		</div>
	</div>
</header>

app/views/layouts/_shim.html.erb
<!--[if lt IE 9]>
<script src="http://html5shim.googlecode.com/svn/trunk/html5.js"></script>
<![endif]-->

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
	<title><%= full_title(yield(:title)) %></title>
	<%= stylesheet_link_tag	"application", media: "all" %>
	<%= javascript_include_tag "application" %>
	<%= csrf_meta_tags %>
	<%= render 'layouts/shim' %>
</head>
<body>
	<%= render 'layouts/header' %>
	<div class="container">
		<%= yield %>
		<%= render 'layouts/footer' %>
	</div>
</body>
</html>

app/views/static_pages/about.html.erb
<% provide(:title, 'About') %>
<h1>
  About
</h1>

<p>
The purpose of this website is to make your life easier when 
managing your soccer matches with your friends.
It allows you to organize a team, make seasons and keep ranking
about player skills throughout the season.
With the Pelada-Manager your soccer games will be much more
organized and easy to mantain.

Your friends will surely thank you.
</p>

app/views/static_pages/contact.html.erb
<% provide(:title, 'Contact') %>
<h1>Contact</h1>
<p>
Contact the developer by using this email <a href="mailto:digaomatias@gmail.com">digaomatias@gmail.com </a> or use the form bellow.
<a href="http://railstutorial.org/contact">contact page</a>.
</p>

app/views/static_pages/help.html.erb
<% provide(:title, 'Help') %>
<h1>Help</h1>
<p>
This is the help page for the
<a href="http://railstutorial.org/">Pelada Manager</a>
App.
</p>
</body>

app/views/static_pages/home.html.erb
<div class="center hero-unit">
	<h1>Pelada Manager</h1>
	
	<h2>
		This is the home page for the
		<a href="http://railstutorial.org/">Pelada Manager</a> App.
	</h2>

	<%= link_to "Sign up now!", signup_path, class: "btn btn-large btn-primary" %>
</div>

<%= link_to image_tag("rails.png", alt: "Rails"), 'http://rubyonrails.org/' %>

app/views/users/new.html.erb
<% provide(:title, 'Sign up') %>
<h1>Sign up</h1>
<p>Find me in app/views/users/new.html.erb</p>